services:
  backend:
    build:
      context: ./tauranet-backend
      dockerfile: Dockerfile
    container_name: tauranet-backend-dev
    ports:
      - "8081:80"
    environment:
      DB_HOST: ${DB_HOST}   # apunta a la BD de producción
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./tauranet-backend:/var/www

  frontend:
    build:
      context: ./tauranet-frontend
      dockerfile: Dockerfile
    container_name: tauranet-frontend-dev
    ports:
      - "8085:8080"
    depends_on:
      - backend
    volumes:
      - ./tauranet-frontend:/app
      - /app/node_modules
